#! /bin/sh
# /etc/init.d/sound-sensor

### BEGIN INIT INFO
# Provides:          sound-sensor
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start a program at boot
# Description:       A simple script from www.stuffaboutcode.com which will start / stop a program a boot / shutdown.
### END INIT INFO

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system

export PATH=$PATH:/usr/local/bin
export NODE_PATH=$NODE_PATH:/user/local/lib/node_modules

case "$1" in
  start)
    echo "Starting sound sensor"
    # run application you want to start
    (cd /home/pi/Sensor-Making/soundSensor_duino/soundSensor_duino/ && sudo forever start app.js)
#/usr/local/bin/noip2
    ;;
  stop)
    echo "Stopping sound sensor"
    # kill application you want to stop
    (sudo forever stop /home/pi/Sensor-Making/soundSensor_duino/soundSensor_duino/app.js)
#    killall noip2
    ;;
  *)
    echo "Usage: /etc/init.d/sound-sensor {start|stop}"
    exit 1
    ;;
esac

exit 0
